ALTER TABLE EMPLOYEE DROP constraint companyFK1 ;
ALTER TABLE EMPLOYEE  DROP constraint companyFK2 ;
ALTER TABLE WORKS_ON DROP constraint companyFK3 ;
ALTER TABLE WORKS_ON  DROP constraint companyFK4 ;
ALTER TABLE DEPT_LOCATIONS  DROP constraint companyFK5;
ALTER TABLE DEPENDENT  DROP constraint companyFK6 ;
ALTER TABLE DEPARTMENT  DROP constraint companyFK7 ;
ALTER TABLE PROJECT  DROP constraint companyFK8 ;


ALTER TABLE DEPARTMENT
ALTER COLUMN Mgr_ssn DROP NOT NULL;

ALTER TABLE DEPARTMENT
ADD CONSTRAINT fk1 FOREIGN KEY (Mgr_ssn) REFERENCES EMPLOYEE(Ssn)
ON DELETE SET NULL
ON UPDATE CASCADE;

ALTER TABLE DEPT_LOCATIONS
ADD CONSTRAINT fk2 FOREIGN KEY (Dnumber) REFERENCES DEPARTMENT(Dnumber)
ON DELETE RESTRICT;

ALTER TABLE Project 
ADD CONSTRAINT fk3 FOREIGN KEY (Dnum) REFERENCES DEPARTMENT(Dnumber)
ON DELETE RESTRICT;

ALTER TABLE WORKS_ON 
ADD CONSTRAINT fk4 FOREIGN KEY (Essn) REFERENCES EMPLOYEE(Ssn)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE WORKS_ON
ADD CONSTRAINT fk5 FOREIGN KEY (Pno) REFERENCES PROJECT(Pnumber)
ON DELETE RESTRICT;

ALTER TABLE DEPENDENT 
ADD CONSTRAINT fk6 FOREIGN KEY (Essn) REFERENCES EMPLOYEE(Ssn)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE EMPLOYEE
ADD CONSTRAINT fk7 FOREIGN KEY (Dno) REFERENCES DEPARTMENT(Dnumber)
ON DELETE RESTRICT;

ALTER TABLE EMPLOYEE
ALTER COLUMN Super_ssn DROP NOT NULL;

ALTER TABLE EMPLOYEE
ADD CONSTRAINT fk8 FOREIGN KEY (Super_ssn) REFERENCES EMPLOYEE(Ssn)
ON DELETE SET NULL
ON UPDATE CASCADE;



INSERT INTO EMPLOYEE(Fname, Minit, Lname, Ssn, Bdate, Address, Sex, Salary, Super_ssn, Dno) VALUES ('Dai','D','Vo','999999999','2002-01-01', '2000 Spruce St., Winnipe, MB','M',25000,'123456789',5);


DELETE FROM EMPLOYEE 
WHERE Fname = 'James' AND Lname = 'Borg';


