ALTER TABLE EMPLOYEE 
ADD COLUMN OfficeNo VARCHAR(5) DEFAULT 'A-0' NULL,
ADD CONSTRAINT OfficeNo_check CHECK (OfficeNo ~ '^[A-Z]-\d{1,3}$');


UPDATE EMPLOYEE
SET OfficeNo CASE
WHEN Dno = 1 THEN 'A-113'
WHEN Dno = 4 THEN 'B-0'
WHEN Dno = 5 THEN 'W-0'
ELSE 'W-0'
END;